backend:
  name: git-gateway
  branch: master
media_folder: public/assets
public_folder: assets
collections:
  - name: "pages"
    label: "Pages"
    files:
      # - label: "Home"
      #   name: "home"
      #   file: "src/content/home.md"
      #   fields:
      #     - { label: "Title", name: "title", widget: "string" }
      #     - { label: "Publish Date", name: "date", widget: "datetime" }
      #     - { label: "Body", name: "body", widget: "markdown" }
      #     - label: "Cats"
      #       name: "cats"
      #       widget: list
      #       fields:
      #         - { label: "Name", name: "name", widget: "string" }
      #         - { label: "Description", name: "description", widget: "text" }
      - label: "About"
        name: "about"
        file: "src/content/about.md"
        fields:
          - label: "About description"
            name: "description"
            widget: list
            fields:
              - { label: "Paragraph", name: "paragraph", widget: "string" }
          - { label: "Partner Section Title", name: "title", widget: "string" }
          - label: "Partners"
            name: "partners"
            widget: list
            fields:
              - { label: "Partner", name: "partner", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
      - label: "Our Supporters"
        name: "our supporters"
        file: "src/content/our-supporters.md"
        fields:
          - { label: "Description", name: "description", widget: "text" }
          - label: "Supporters"
            name: "supporters"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              # - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "text" }
              - {
                  label: "Card Background Color",
                  name: "cardColor",
                  widget: "text",
                }
      - label: "Join In"
        name: "join in"
        file: "src/content/join-in.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
      - label: "Login"
        name: "login"
        file: "src/content/login.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
      - label: "Research Home"
        name: "research home"
        file: "src/content/research-home.md"
        fields:
          - { label: "Section1", name: "section1", widget: "string" }
          - { label: "Section2", name: "section2", widget: "string" }
          - { label: "Section3", name: "section3", widget: "string" }
      - label: "Research Sub Pages"
        name: "research sub pages"
        file: "src/content/research-sub-page.md"
        fields:
          - label: "Security and Sovereignty"
            name: "security and sovereignty"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Description"
                name: "description"
                widget: "list"
                fields:
                  - { label: "Paragraph", name: "paragraph", widget: "string" }
              - label: "Research"
                name: "research"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                    }
          - label: "The Digital Citizen"
            name: "the digital citizen"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Description"
                name: "description"
                widget: "list"
                fields:
                  - { label: "Paragraph", name: "paragraph", widget: "string" }
              - label: "Research"
                name: "research"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                    }
          - label: "The Digital Commons"
            name: "security and sovereignty"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Description"
                name: "description"
                widget: "list"
                fields:
                  - { label: "Paragraph", name: "paragraph", widget: "string" }
              - label: "Research"
                name: "research"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                    }
