backend:
  name: git-gateway
  branch: master
media_folder: public/assets
public_folder: assets
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
      - label: "About"
        name: "about"
        file: "src/content/about.md"
        fields:
          - label: "Description"
            name: "description"
            widget: list
            fields:
              - { label: "Paragraph", name: "paragraph", widget: "string" }
          - label: "Project Partners"
            name: "projectPartners"
            widget: list
            fields:
              - { label: "Section title", name: "title", widget: "string" }
              - label: "Partners"
                name: "partners"
                widget: list
                fields:
                  - { label: "Partner", name: "partner", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                    }
